"""
schemas/report.py — Pydantic v2 schemas for the Report Compiler agent.

The Report Compiler aggregates all agent outputs into a structured
Markdown (and optionally PDF) project proposal report.

Expected LLM JSON output example (ReportResponse):
────────────────────────────────────────────────────
{
  "report_metadata": {
    "generated_at": "2025-01-15T12:45:00+00:00",
    "pipeline_version": "1.0.0",
    "total_execution_time_minutes": 42,
    "task_id": "a3f8c2d1-4e56-7890-abcd-ef1234567890",
    "llm_model": "gemma4:31b-it-q8_0"
  },
  "executive_summary": "## Executive Summary\n\nThis proposal ...",
  "headline": "EGFR Kinase Inhibition for Third-Line NSCLC Treatment",
  "sections": {
    "target_selection": {
      "section_name": "Target Selection",
      "content": "## Target Selection\n\n...",
      "key_points": ["EGFR overexpressed in 85% of NSCLC"],
      "word_count": 312
    },
    ...
  },
  "markdown_report_path": "outputs/reports/proposal_20250115_124500.md",
  "pdf_report_path": null,
  "caveats": ["Docking scores are mock estimates (Vina not available)"]
}
"""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field, field_validator, model_validator


class ReportMetadata(BaseModel):
    """
    Metadata block included at the top of every generated report.

    Provides full reproducibility information: when the report was generated,
    which model produced it, and how long the pipeline took.
    """

    generated_at: str = Field(
        ...,
        description="ISO-8601 UTC timestamp of report generation.",
        min_length=10,
    )
    pipeline_version: str = Field(
        ...,
        description="Pipeline software version string (e.g. '1.0.0').",
        min_length=1,
    )
    total_execution_time_minutes: float = Field(
        ...,
        description="Total pipeline wall-clock time in minutes.",
        ge=0.0,
    )
    task_id: str = Field(
        ...,
        description="UUID4 identifying this pipeline run.",
        min_length=1,
    )
    llm_model: str = Field(
        ...,
        description="Ollama LLM model used for all agent calls.",
        min_length=1,
    )
    indication: Optional[str] = Field(
        default=None,
        description="Disease indication or biological target passed as pipeline input.",
    )
    papers_reviewed: Optional[int] = Field(
        default=None,
        description="Total scientific papers reviewed during retrieval.",
        ge=0,
    )
    patents_reviewed: Optional[int] = Field(
        default=None,
        description="Total patents reviewed during retrieval.",
        ge=0,
    )
    molecules_generated: Optional[int] = Field(
        default=None,
        description="Total molecules generated by the Molecule Designer.",
        ge=0,
    )
    molecules_shortlisted: Optional[int] = Field(
        default=None,
        description="Molecules shortlisted after drug-likeness filtering.",
        ge=0,
    )
    docking_performed: bool = Field(
        default=True,
        description="Whether AutoDock Vina docking was performed (or mocked).",
    )
    synthesis_evaluated: bool = Field(
        default=False,
        description="Whether chemical synthesis routes were evaluated.",
    )

    @field_validator("total_execution_time_minutes", mode="before")
    @classmethod
    def coerce_time(cls, v: object) -> float:
        """Accept int or float execution times."""
        try:
            return max(0.0, float(v))
        except (TypeError, ValueError):
            return 0.0


class ReportSection(BaseModel):
    """
    A single section of the project proposal report.

    Each section is written by the LLM based on the relevant agent output,
    then assembled by the Report Compiler into the final Markdown document.
    """

    section_name: str = Field(
        ...,
        description=(
            "Display name for this section "
            "(e.g. 'Target Selection', 'Lead Compound Analysis')."
        ),
        min_length=1,
        max_length=100,
    )
    content: str = Field(
        ...,
        description=(
            "Full section content in GitHub-flavoured Markdown format. "
            "Should include appropriate headers (##, ###), bullet points, "
            "and tables where relevant."
        ),
        min_length=50,
    )
    key_points: list[str] = Field(
        default_factory=list,
        description=(
            "3-5 key takeaway bullet points for the executive summary "
            "and slide deck. Each < 150 characters."
        ),
        max_length=10,
    )
    word_count: int = Field(
        default=0,
        description="Approximate word count of the content field.",
        ge=0,
    )

    @field_validator("key_points", mode="before")
    @classmethod
    def coerce_key_points(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    @field_validator("word_count", mode="before")
    @classmethod
    def coerce_word_count(cls, v: object) -> int:
        """Accept None as 0."""
        if v is None:
            return 0
        try:
            return max(0, int(v))
        except (TypeError, ValueError):
            return 0

    @model_validator(mode="after")
    def auto_count_words(self) -> "ReportSection":
        """
        Auto-calculate word count from content if not provided or is 0.

        Returns:
            ReportSection: Self with word_count populated.
        """
        if self.word_count == 0 and self.content:
            self.word_count = len(self.content.split())
        return self


class ReportSections(BaseModel):
    """
    Container for all report sections, keyed by section identifier.

    Each field corresponds to one pipeline phase's contribution to the
    final proposal. Optional sections (synthesis) are None when disabled.
    """

    executive_summary: Optional[ReportSection] = Field(
        default=None,
        description="Executive summary section (generated last, placed first).",
    )
    target_selection: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section describing the target identification and selection process, "
            "including literature evidence and druggability assessment."
        ),
    )
    hypothesis: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section describing the mechanistic hypothesis, including the "
            "proposed mechanism of action and supporting evidence."
        ),
    )
    molecule_design: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section describing the computational molecule design process, "
            "design strategy, and key properties of shortlisted candidates."
        ),
    )
    docking_analysis: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section presenting molecular docking results, lead compound "
            "selection rationale, and key binding interactions."
        ),
    )
    synthesis_plan: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section proposing synthetic routes for the lead compound. "
            "None when ENABLE_CHEMICAL_SYNTHESIS=False."
        ),
    )
    next_steps: Optional[ReportSection] = Field(
        default=None,
        description=(
            "Section outlining recommended next development steps: "
            "experimental validation, ADMET profiling, lead optimisation."
        ),
    )

    def get_all_sections(self) -> list[ReportSection]:
        """
        Return all non-None sections in report order.

        Returns:
            list[ReportSection]: Ordered list of populated sections.
        """
        ordered_keys = [
            "executive_summary",
            "target_selection",
            "hypothesis",
            "molecule_design",
            "docking_analysis",
            "synthesis_plan",
            "next_steps",
        ]
        sections: list[ReportSection] = []
        for key in ordered_keys:
            section = getattr(self, key, None)
            if section is not None:
                sections.append(section)
        return sections

    def total_word_count(self) -> int:
        """
        Calculate the total word count across all sections.

        Returns:
            int: Sum of word counts for all populated sections.
        """
        return sum(s.word_count for s in self.get_all_sections())

    def to_markdown(self) -> str:
        """
        Assemble all sections into a single Markdown document string.

        Sections are joined with double newlines for spacing.
        The executive_summary section is placed first regardless of
        insertion order.

        Returns:
            str: Full Markdown document string.
        """
        parts: list[str] = []
        for section in self.get_all_sections():
            parts.append(section.content)
        return "\n\n---\n\n".join(parts)

    def all_key_points(self) -> list[str]:
        """
        Collect key points from all sections for slide deck generation.

        Returns:
            list[str]: All key points across all sections.
        """
        points: list[str] = []
        for section in self.get_all_sections():
            points.extend(section.key_points)
        return points


class ReportResponse(BaseModel):
    """
    Full output schema for the Report Compiler agent.

    This is the final artifact produced by the pipeline. The markdown_report_path
    field points to the saved .md file; pdf_report_path is populated only when
    ENABLE_PDF_REPORT=True and a PDF converter is available.
    """

    report_metadata: ReportMetadata = Field(
        ...,
        description="Full metadata block for the report.",
    )
    headline: str = Field(
        ...,
        description=(
            "One-line project title for the proposal "
            "(e.g. 'EGFR Kinase Inhibition for Third-Line NSCLC Treatment')."
        ),
        min_length=10,
        max_length=200,
    )
    executive_summary: str = Field(
        ...,
        description=(
            "200-300 word executive summary in Markdown format. "
            "Placed at the top of the final report."
        ),
        min_length=100,
    )
    sections: ReportSections = Field(
        ...,
        description="All report sections assembled by the Report Compiler.",
    )
    markdown_report_path: str = Field(
        ...,
        description=(
            "Relative path to the saved Markdown report file "
            "(e.g. 'outputs/reports/proposal_20250115_124500.md')."
        ),
        min_length=5,
    )
    pdf_report_path: Optional[str] = Field(
        default=None,
        description=(
            "Relative path to the saved PDF report file. "
            "Null if ENABLE_PDF_REPORT=False or PDF conversion failed."
        ),
    )
    caveats: list[str] = Field(
        default_factory=list,
        description=(
            "List of important caveats about the report's reliability. "
            "Examples: mock docking scores, missing PDB structures, "
            "failed patent searches."
        ),
    )
    development_stage: str = Field(
        default="Hit Identification",
        description=(
            "Current drug discovery stage for this project "
            "(always 'Hit Identification' for pipeline output)."
        ),
    )

    @field_validator("caveats", mode="before")
    @classmethod
    def coerce_caveats(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    @field_validator("executive_summary", mode="before")
    @classmethod
    def strip_executive_summary(cls, v: str) -> str:
        """Strip excess whitespace from the executive summary."""
        return v.strip()

    def to_full_markdown(self) -> str:
        """
        Generate the complete Markdown document including header metadata.

        Produces a document with:
          - YAML frontmatter for metadata
          - Headline as H1
          - Executive summary
          - All report sections
          - Caveats appendix

        Returns:
            str: Complete Markdown report string.
        """
        meta = self.report_metadata

        # ── YAML frontmatter ─────────────────────────────────────────────────
        frontmatter = (
            "---\n"
            f"title: \"{self.headline}\"\n"
            f"generated_at: \"{meta.generated_at}\"\n"
            f"pipeline_version: \"{meta.pipeline_version}\"\n"
            f"task_id: \"{meta.task_id}\"\n"
            f"llm_model: \"{meta.llm_model}\"\n"
            f"development_stage: \"{self.development_stage}\"\n"
            "---\n\n"
        )

        # ── Header ───────────────────────────────────────────────────────────
        header = (
            f"# {self.headline}\n\n"
            f"**Development Stage:** {self.development_stage}  \n"
            f"**Generated:** {meta.generated_at}  \n"
            f"**Pipeline Version:** {meta.pipeline_version}  \n"
            f"**LLM Model:** {meta.llm_model}  \n\n"
        )

        # ── Pipeline statistics ───────────────────────────────────────────────
        stats_lines = ["## Pipeline Statistics\n"]
        if meta.papers_reviewed is not None:
            stats_lines.append(f"- **Papers reviewed:** {meta.papers_reviewed}")
        if meta.patents_reviewed is not None:
            stats_lines.append(f"- **Patents reviewed:** {meta.patents_reviewed}")
        if meta.molecules_generated is not None:
            stats_lines.append(
                f"- **Molecules generated:** {meta.molecules_generated}"
            )
        if meta.molecules_shortlisted is not None:
            stats_lines.append(
                f"- **Molecules shortlisted:** {meta.molecules_shortlisted}"
            )
        stats_lines.append(
            f"- **Docking performed:** {'Yes' if meta.docking_performed else 'No'}"
        )
        stats_lines.append(
            f"- **Synthesis evaluated:** "
            f"{'Yes' if meta.synthesis_evaluated else 'No'}"
        )
        stats_lines.append(
            f"- **Total execution time:** "
            f"{meta.total_execution_time_minutes:.1f} minutes"
        )
        stats_block = "\n".join(stats_lines) + "\n\n"

        # ── Executive summary ─────────────────────────────────────────────────
        exec_summary = f"## Executive Summary\n\n{self.executive_summary}\n\n"

        # ── Body sections ─────────────────────────────────────────────────────
        body = self.sections.to_markdown()

        # ── Caveats appendix ──────────────────────────────────────────────────
        caveats_block = ""
        if self.caveats:
            caveat_lines = ["## ⚠️ Important Caveats\n"]
            caveat_lines.extend(f"- {c}" for c in self.caveats)
            caveats_block = "\n".join(caveat_lines) + "\n\n"

        # ── Footer ────────────────────────────────────────────────────────────
        footer = (
            "\n\n---\n\n"
            "*This report was generated automatically by the Drug Discovery "
            "Hypothesis-to-Report Pipeline. All findings require experimental "
            "validation before any clinical or investment decisions are made.*\n"
        )

        return (
            frontmatter
            + header
            + stats_block
            + exec_summary
            + "---\n\n"
            + body
            + "\n\n"
            + caveats_block
            + footer
        )

    def word_count(self) -> int:
        """
        Calculate total word count of the full Markdown report.

        Returns:
            int: Total words including all sections and executive summary.
        """
        full_doc = self.to_full_markdown()
        return len(full_doc.split())

    model_config = {
        "json_schema_extra": {
            "example": {
                "report_metadata": {
                    "generated_at": "2025-01-15T12:45:00+00:00",
                    "pipeline_version": "1.0.0",
                    "total_execution_time_minutes": 42.3,
                    "task_id": "a3f8c2d1-4e56-7890-abcd-ef1234567890",
                    "llm_model": "gemma4:31b-it-q8_0",
                    "indication": "non-small cell lung cancer",
                    "papers_reviewed": 150,
                    "patents_reviewed": 45,
                    "molecules_generated": 20,
                    "molecules_shortlisted": 5,
                    "docking_performed": True,
                    "synthesis_evaluated": False,
                },
                "headline": (
                    "EGFR Kinase Inhibition for Third-Line NSCLC Treatment"
                ),
                "executive_summary": (
                    "Non-small cell lung cancer (NSCLC) represents 85% of all "
                    "lung cancer cases with a 5-year survival rate of 19%..."
                ),
                "sections": {},
                "markdown_report_path": (
                    "outputs/reports/proposal_20250115_124500.md"
                ),
                "pdf_report_path": None,
                "caveats": [
                    "Docking scores are real Vina results (AutoDock Vina 1.2.3).",
                    "Synthesis routes are LLM-proposed and require expert review.",
                ],
                "development_stage": "Hit Identification",
            }
        }
    }