"""
agents/report_compiler.py — Report Compiler agent: final proposal generation.

The Report Compiler is Phase 6 (final phase) of the pipeline. It:
  1. Collects compressed outputs from all previous agents.
  2. Calls the LLM once per report section to write professional prose.
  3. Calls the LLM once more to write the executive summary.
  4. Assembles all sections into a complete Markdown document.
  5. Saves the document to outputs/reports/.
  6. Optionally generates a PDF if ENABLE_PDF_REPORT=True.
  7. Returns the final ReportResponse dict.

Report sections:
  1. Executive Summary (generated last, placed first)
  2. Target Selection
  3. Mechanistic Hypothesis
  4. Molecule Design
  5. Docking Analysis
  6. Synthesis Plan (only if ENABLE_CHEMICAL_SYNTHESIS=True)
  7. Next Steps & Recommendations

Output schema: schemas.ReportResponse
"""

from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from loguru import logger

from config import (
    FeatureFlags,
    ModelConfig,
    PipelineConfig,
)
from schemas import (
    DockingResponse,
    HypothesisResponse,
    MoleculeDesignResponse,
    ReportMetadata,
    ReportResponse,
    ReportSection,
    ReportSections,
    RetrieverResponse,
    SynthesisResponse,
)
from utils.ollama_client import OllamaClient
from utils.prompts import (
    REPORT_SECTION_PROMPT,
    REPORT_EXECUTIVE_SUMMARY_PROMPT,
    SYSTEM_REPORTER,
    JSON_ENFORCEMENT,
    build_agent_prompt,
)
from utils.helpers import (
    log_json_event,
    utc_now_iso,
    safe_json_dumps,
    write_text_file,
    generate_output_filename,
    format_duration,
)
from utils.json_validator import JSONValidator
from utils.context_manager import ContextManager


class ReportCompilerAgent:
    """
    Compiles all pipeline agent outputs into a formatted project proposal.

    Each report section is generated by a separate LLM call, using only
    the compressed data relevant to that section. This keeps each call
    within the token budget while producing detailed section-level content.

    Usage:
        agent = ReportCompilerAgent(ollama_client=client)
        result = await agent.run(state)
        # result is a dict matching ReportResponse schema
        # report saved to outputs/reports/proposal_YYYYMMDD_HHMMSS.md
    """

    def __init__(self, ollama_client: OllamaClient) -> None:
        """
        Initialise the Report Compiler agent.

        Args:
            ollama_client: Shared OllamaClient instance.
        """
        self.client = ollama_client
        self.ctx = ContextManager()

    async def run(self, state: dict) -> dict:
        """
        Execute the report compilation phase.

        Steps:
            1. Parse all agent outputs from state.
            2. Generate each report section via LLM.
            3. Generate executive summary.
            4. Assemble full Markdown document.
            5. Save to disk.
            6. Optionally convert to PDF.
            7. Return validated ReportResponse dict.

        Args:
            state: Full pipeline state dict with all agent results.

        Returns:
            dict: Validated ReportResponse as a dictionary.
        """
        indication = state["indication_or_target"]
        task_id = state.get("task_id", "unknown")
        started_at = state.get("started_at", utc_now_iso())

        logger.info(f"[ReportCompiler] Compiling proposal for: '{indication}'")

        # ── Parse all agent outputs ───────────────────────────────────────────
        retrieval = self._safe_parse(state.get("retrieval_result"), RetrieverResponse)
        hypothesis = self._safe_parse(state.get("hypothesis_result"), HypothesisResponse)
        mol_design = self._safe_parse(
            state.get("molecule_design_result"), MoleculeDesignResponse
        )
        docking = self._safe_parse(state.get("docking_result"), DockingResponse)
        synthesis = self._safe_parse(state.get("synthesis_result"), SynthesisResponse)

        if not hypothesis:
            raise RuntimeError(
                "[ReportCompiler] hypothesis_result missing — cannot compile report."
            )

        target = hypothesis.selected_target

        # ── Collect caveats ───────────────────────────────────────────────────
        caveats = self._collect_caveats(docking, synthesis, retrieval)

        # ── Generate report sections ──────────────────────────────────────────
        sections = ReportSections()

        sections.target_selection = await self._generate_section(
            section_name="Target Selection",
            indication=indication,
            data={
                "indication": indication,
                "selected_target": target.to_prompt_dict() if target else {},
                "alternative_targets": [
                    t.model_dump() for t in hypothesis.alternative_targets
                ],
                "retrieval_stats": {
                    "papers_reviewed": retrieval.total_papers_reviewed if retrieval else 0,
                    "patents_reviewed": retrieval.total_patents_reviewed if retrieval else 0,
                },
                "hypothesis_confidence": hypothesis.hypothesis.confidence_score,
            },
            target_word_count=350,
        )

        sections.hypothesis = await self._generate_section(
            section_name="Mechanistic Hypothesis",
            indication=indication,
            data={
                "selected_target": target.to_prompt_dict() if target else {},
                "mechanism": hypothesis.hypothesis.mechanism,
                "rationale": hypothesis.hypothesis.rationale,
                "therapeutic_modality": hypothesis.hypothesis.therapeutic_modality,
                "confidence_score": hypothesis.hypothesis.confidence_score,
            },
            target_word_count=400,
        )

        if mol_design:
            sections.molecule_design = await self._generate_section(
                section_name="Molecule Design",
                indication=indication,
                data=mol_design.to_prompt_dict(),
                target_word_count=400,
            )

        if docking:
            sections.docking_analysis = await self._generate_section(
                section_name="Docking Analysis",
                indication=indication,
                data=docking.to_prompt_dict(),
                target_word_count=400,
            )

        if synthesis and synthesis.synthesis_enabled:
            sections.synthesis_plan = await self._generate_section(
                section_name="Synthesis Plan",
                indication=indication,
                data=synthesis.to_prompt_dict(),
                target_word_count=350,
            )

        sections.next_steps = await self._generate_section(
            section_name="Next Steps & Recommendations",
            indication=indication,
            data={
                "indication": indication,
                "target": target.gene_name if target else "unknown",
                "development_stage": "Hit Identification",
                "lead_compound_identified": docking is not None,
                "synthesis_evaluated": synthesis.synthesis_enabled if synthesis else False,
                "confidence_score": hypothesis.hypothesis.confidence_score,
            },
            target_word_count=300,
        )

        # ── Generate executive summary ─────────────────────────────────────────
        exec_summary_data = await self._generate_executive_summary(
            indication=indication,
            hypothesis=hypothesis,
            docking=docking,
            state=state,
        )

        # ── Assemble metadata ─────────────────────────────────────────────────
        elapsed_seconds = sum(state.get("phase_timings", {}).values())
        elapsed_minutes = round(elapsed_seconds / 60, 1)

        metadata = ReportMetadata(
            generated_at=utc_now_iso(),
            pipeline_version=PipelineConfig.VERSION,
            total_execution_time_minutes=elapsed_minutes,
            task_id=task_id,
            llm_model=state.get("llm_model", ModelConfig.LLM_MODEL),
            indication=indication,
            papers_reviewed=retrieval.total_papers_reviewed if retrieval else None,
            patents_reviewed=retrieval.total_patents_reviewed if retrieval else None,
            molecules_generated=(
                len(mol_design.generated_molecules) if mol_design else None
            ),
            molecules_shortlisted=(
                mol_design.shortlisted_count if mol_design else None
            ),
            docking_performed=docking is not None,
            synthesis_evaluated=(
                synthesis.synthesis_enabled if synthesis else False
            ),
        )

        # ── Determine output path ─────────────────────────────────────────────
        output_dir = Path("outputs/reports")
        output_dir.mkdir(parents=True, exist_ok=True)
        filename = generate_output_filename("proposal", "md")
        report_path = output_dir / filename

        # ── Build ReportResponse ──────────────────────────────────────────────
        response = ReportResponse(
            report_metadata=metadata,
            headline=exec_summary_data.get(
                "headline",
                f"{target.gene_name if target else 'Target'} Inhibition "
                f"for {indication.title()} Treatment",
            ),
            executive_summary=exec_summary_data.get(
                "executive_summary",
                f"Pipeline completed for {indication}.",
            ),
            sections=sections,
            markdown_report_path=str(report_path),
            pdf_report_path=None,
            caveats=caveats,
            development_stage="Hit Identification",
        )

        # ── Save Markdown report ──────────────────────────────────────────────
        full_markdown = response.to_full_markdown()
        write_text_file(report_path, full_markdown)
        logger.success(f"[ReportCompiler] Markdown report saved: {report_path}")

        # ── Optional PDF generation ───────────────────────────────────────────
        if FeatureFlags.ENABLE_PDF_REPORT:
            pdf_path = await self._generate_pdf(report_path)
            if pdf_path:
                response.pdf_report_path = str(pdf_path)

        # ── Log ───────────────────────────────────────────────────────────────
        log_json_event(
            PipelineConfig.PIPELINE_LOG,
            {
                "event": "report_compiler_output",
                "task_id": task_id,
                "report_path": str(report_path),
                "pdf_path": response.pdf_report_path,
                "total_words": response.word_count(),
                "sections_generated": len(sections.get_all_sections()),
                "caveats": caveats,
                "elapsed_minutes": elapsed_minutes,
                "timestamp": utc_now_iso(),
            },
        )

        logger.success(
            f"[ReportCompiler] Report complete. "
            f"Words: {response.word_count()}. "
            f"Sections: {len(sections.get_all_sections())}. "
            f"Elapsed: {format_duration(elapsed_seconds)}."
        )

        return response.model_dump()

    # ── Section generation ────────────────────────────────────────────────────
    async def _generate_section(
        self,
        section_name: str,
        indication: str,
        data: dict,
        target_word_count: int = 350,
    ) -> ReportSection:
        """
        Generate a single report section via LLM call.

        Compresses `data` to fit within token budget before calling LLM.

        Args:
            section_name: Display name for this section (e.g. "Target Selection").
            indication: Disease/target for context.
            data: Section-specific data dict (agent output, compressed).
            target_word_count: Approximate word count to request from LLM.

        Returns:
            ReportSection: Validated section with content and key_points.
        """
        data_json = safe_json_dumps(data, indent=2)
        data_json = self.ctx.truncate_to_tokens(data_json, 2500)

        user_prompt = REPORT_SECTION_PROMPT.format(
            section_name=section_name,
            indication_or_target=indication,
            section_data_json=data_json,
            target_word_count=target_word_count,
            json_enforcement=JSON_ENFORCEMENT,
        )

        messages = build_agent_prompt(
            system=SYSTEM_REPORTER,
            user=user_prompt,
            assistant_primer="{",
        )

        try:
            raw_response = await self.client.chat(
                messages=messages,
                schema=ReportSection,
                temperature=0.6,
                context_label=f"report_{section_name.lower().replace(' ', '_')}",
            )
            parsed = JSONValidator.assert_valid(raw_response, ReportSection)
            parsed["section_name"] = section_name
            return ReportSection.model_validate(parsed)

        except Exception as exc:  # noqa: BLE001
            logger.warning(
                f"[ReportCompiler] Section '{section_name}' generation failed: {exc}. "
                "Using fallback section."
            )
            return self._fallback_section(section_name, data)

    async def _generate_executive_summary(
        self,
        indication: str,
        hypothesis: HypothesisResponse,
        docking: Optional[DockingResponse],
        state: dict,
    ) -> dict:
        """
        Generate the executive summary via LLM call.

        Uses the lead compound and key findings from all agents.

        Args:
            indication: Disease/target indication.
            hypothesis: Validated HypothesisResponse.
            docking: Validated DockingResponse (may be None).
            state: Full pipeline state for timing metadata.

        Returns:
            dict: Parsed executive summary with 'executive_summary' and 'headline'.
        """
        target = hypothesis.selected_target
        lead_smiles = "N/A"
        binding_affinity = "N/A"

        if docking:
            lead_smiles = docking.lead_compound_smiles
            lead = docking.get_lead()
            binding_affinity = f"{lead.binding_affinity_kcal_mol} kcal/mol"

        elapsed_seconds = sum(state.get("phase_timings", {}).values())
        elapsed_minutes = round(elapsed_seconds / 60, 1)

        key_findings = {
            "target": target.gene_name,
            "target_class": target.target_class,
            "mechanism_summary": hypothesis.hypothesis.mechanism[:200],
            "confidence": hypothesis.hypothesis.confidence_score,
            "lead_smiles": lead_smiles[:50] if lead_smiles != "N/A" else "N/A",
            "binding_affinity": binding_affinity,
            "alternative_targets": [t.gene_name for t in hypothesis.alternative_targets],
        }

        user_prompt = REPORT_EXECUTIVE_SUMMARY_PROMPT.format(
            indication_or_target=indication,
            gene_name=target.gene_name,
            uniprot_id=target.uniprot_id,
            lead_smiles=lead_smiles[:60] if lead_smiles != "N/A" else "N/A",
            binding_affinity=binding_affinity,
            execution_time_minutes=elapsed_minutes,
            key_findings_json=safe_json_dumps(key_findings, indent=2),
            json_enforcement=JSON_ENFORCEMENT,
        )

        messages = build_agent_prompt(
            system=SYSTEM_REPORTER,
            user=user_prompt,
            assistant_primer="{",
        )

        try:
            from schemas.report import ReportResponse as _ReportResponseClass
            # Use a simple inline schema for the exec summary call
            from pydantic import BaseModel

            class ExecSummarySchema(BaseModel):
                executive_summary: str
                headline: str
                development_stage: str
                target_indication: str

            raw_response = await self.client.chat(
                messages=messages,
                schema=ExecSummarySchema,
                temperature=0.6,
                context_label="report_executive_summary",
            )
            parsed = JSONValidator.assert_valid(raw_response, ExecSummarySchema)
            return parsed

        except Exception as exc:  # noqa: BLE001
            logger.warning(
                f"[ReportCompiler] Executive summary generation failed: {exc}. "
                "Using fallback summary."
            )
            return {
                "executive_summary": (
                    f"This proposal presents a drug discovery project targeting "
                    f"**{target.gene_name}** for the treatment of "
                    f"**{indication}**. "
                    f"The pipeline identified {target.gene_name} as the primary "
                    f"druggable target with confidence score "
                    f"{hypothesis.hypothesis.confidence_score:.2f}. "
                    f"Lead compound affinity: {binding_affinity}."
                ),
                "headline": (
                    f"{target.gene_name} Inhibition for {indication.title()} Treatment"
                ),
                "development_stage": "Hit Identification",
                "target_indication": indication,
            }

    # ── PDF generation ────────────────────────────────────────────────────────
    async def _generate_pdf(self, markdown_path: Path) -> Optional[Path]:
        """
        Convert the Markdown report to PDF using pandoc or weasyprint.

        Attempts pandoc first (most flexible), then weasyprint.
        Returns None if neither is available.

        Args:
            markdown_path: Path to the saved Markdown report.

        Returns:
            Path | None: Path to the saved PDF file, or None on failure.
        """
        pdf_path = markdown_path.with_suffix(".pdf")

        # Try pandoc first
        try:
            import subprocess
            import shutil

            if shutil.which("pandoc"):
                result = subprocess.run(
                    [
                        "pandoc",
                        str(markdown_path),
                        "-o", str(pdf_path),
                        "--pdf-engine=xelatex",
                        "-V", "geometry:margin=2.5cm",
                        "-V", "fontsize=11pt",
                    ],
                    capture_output=True,
                    text=True,
                    timeout=60,
                )
                if result.returncode == 0 and pdf_path.exists():
                    logger.success(
                        f"[ReportCompiler] PDF generated via pandoc: {pdf_path}"
                    )
                    return pdf_path
                else:
                    logger.debug(
                        f"[ReportCompiler] pandoc failed: {result.stderr[:200]}"
                    )
        except Exception as exc:  # noqa: BLE001
            logger.debug(f"[ReportCompiler] pandoc unavailable: {exc}")

        # Try weasyprint
        try:
            import markdown as md_lib
            from weasyprint import HTML

            html_content = md_lib.markdown(
                markdown_path.read_text(encoding="utf-8"),
                extensions=["tables", "fenced_code", "toc"],
            )
            html_full = (
                "<html><head><meta charset='utf-8'>"
                "<style>body{font-family:Arial,sans-serif;margin:2.5cm;}"
                "h1,h2,h3{color:#2c3e50;}table{border-collapse:collapse;}"
                "td,th{border:1px solid #ccc;padding:8px;}"
                "</style></head><body>"
                f"{html_content}</body></html>"
            )
            HTML(string=html_full).write_pdf(str(pdf_path))
            logger.success(
                f"[ReportCompiler] PDF generated via weasyprint: {pdf_path}"
            )
            return pdf_path

        except ImportError:
            logger.info(
                "[ReportCompiler] Neither pandoc nor weasyprint available. "
                "PDF generation skipped. "
                "Install: pip install weasyprint  OR  brew install pandoc"
            )
        except Exception as exc:  # noqa: BLE001
            logger.warning(f"[ReportCompiler] PDF generation failed: {exc}")

        return None

    # ── Caveat collection ─────────────────────────────────────────────────────
    @staticmethod
    def _collect_caveats(
        docking: Optional[DockingResponse],
        synthesis: Optional[SynthesisResponse],
        retrieval: Optional[RetrieverResponse],
    ) -> list[str]:
        """
        Collect data quality caveats to include in the final report.

        Args:
            docking: Validated DockingResponse (may be None).
            synthesis: Validated SynthesisResponse (may be None).
            retrieval: Validated RetrieverResponse (may be None).

        Returns:
            list[str]: List of caveat strings for the report appendix.
        """
        caveats: list[str] = [
            "All findings are computationally predicted and require "
            "experimental validation before clinical or investment decisions.",
            "Molecular docking scores are estimates and do not account for "
            "protein flexibility, solvent effects, or ADMET properties.",
        ]

        if docking and docking.contains_mock_results:
            caveats.append(
                "⚠️ DOCKING SCORES ARE MOCK ESTIMATES: AutoDock Vina was not "
                "available. Scores were estimated from molecular properties only. "
                "Run with Vina installed for real docking results."
            )

        if synthesis and not synthesis.synthesis_enabled:
            caveats.append(
                "Chemical synthesis routes were not evaluated "
                "(ENABLE_CHEMICAL_SYNTHESIS=False). "
                "Enable this feature for synthetic route proposals."
            )
        elif synthesis and synthesis.synthesis_enabled:
            caveats.append(
                "Synthesis routes are LLM-proposed and have not been "
                "experimentally verified. Consult a synthetic chemist "
                "before attempting any described synthesis."
            )

        if retrieval and retrieval.total_patents_reviewed == 0:
            caveats.append(
                "Patent search was disabled or returned no results. "
                "A freedom-to-operate analysis should be conducted "
                "before advancing candidates."
            )

        return caveats

    # ── Fallback section ──────────────────────────────────────────────────────
    @staticmethod
    def _fallback_section(section_name: str, data: dict) -> ReportSection:
        """
        Generate a minimal fallback section when LLM call fails.

        Args:
            section_name: Name of the section that failed.
            data: Data dict that was passed to the LLM.

        Returns:
            ReportSection: Minimal stub section.
        """
        return ReportSection(
            section_name=section_name,
            content=(
                f"## {section_name}\n\n"
                f"*Section generation failed. Raw data:*\n\n"
                f"```json\n{json.dumps(data, indent=2, default=str)[:500]}\n```\n"
            ),
            key_points=[f"{section_name} data available but section rendering failed."],
            word_count=30,
        )

    # ── Safe model parsing ────────────────────────────────────────────────────
    @staticmethod
    def _safe_parse(raw: Any, model_class: Any) -> Any:
        """
        Safely parse a raw dict into a Pydantic model, returning None on failure.

        Args:
            raw: Raw dict from pipeline state.
            model_class: Pydantic BaseModel subclass to parse into.

        Returns:
            model_class instance or None.
        """
        if not raw:
            return None
        try:
            return model_class.model_validate(raw)
        except Exception as exc:  # noqa: BLE001
            logger.warning(
                f"[ReportCompiler] Failed to parse {model_class.__name__}: {exc}"
            )
            return None