"""
schemas/molecule.py — Pydantic v2 schemas for Molecule Designer and
                      Synthesis Evaluator agents.

The Molecule Designer generates novel SMILES strings and calculates
RDKit-derived physicochemical properties. The Synthesis Evaluator
(optional) proposes synthetic routes for the top-ranked molecules.

Expected LLM JSON output example (MoleculeDesignResponse):
───────────────────────────────────────────────────────────
{
  "generated_molecules": [
    {
      "smiles": "CCN(CC)CCNC(=O)c1ccc2ncnc(Nc3ccc(F)c(Cl)c3)c2c1",
      "name": "Compound-001",
      "generation_method": "scaffold_decoration",
      "design_rationale": "Quinazoline scaffold with fluorochlorophenyl amine.",
      "predicted_interactions": ["H-bond with Met793", "Van der Waals with Leu718"]
    }
  ],
  "design_strategy": "Decoration of quinazoline scaffold with amine linkers.",
  "reference_scaffold": "c1ccc2ncncc2c1"
}

Expected LLM JSON output example (MoleculeDesignResponse — post RDKit filtering):
──────────────────────────────────────────────────────────────────────────────────
{
  "generated_molecules": [...],
  "shortlisted_count": 5,
  "filtering_criteria": {
    "max_molecular_weight": 500.0,
    "max_logp": 5.0,
    "max_hbd": 5,
    "max_hba": 10,
    "min_qed_score": 0.5,
    "max_sa_score": 4.0,
    "max_lipinski_violations": 1
  }
}
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator


# ── Valid generation methods ───────────────────────────────────────────────────
GenerationMethod = Literal[
    "scaffold_decoration",
    "bioisostere",
    "fragment_merge",
    "de_novo",
    "analogue_search",
    "pharmacophore_based",
]

# ── Valid synthesis feasibility levels ────────────────────────────────────────
FeasibilityLevel = Literal["high", "medium", "low"]


class GeneratedMolecule(BaseModel):
    """
    A single molecule generated by the Molecule Designer agent.

    Contains the SMILES string (LLM-generated) and physicochemical
    properties calculated by RDKit (added by the agent, not the LLM).

    Note on property calculation
    ─────────────────────────────
    The LLM provides SMILES and design metadata. The agent then uses
    RDKit to calculate all numeric properties (MW, LogP, QED, SA score,
    Lipinski violations) and populates those fields. The LLM fields
    are: smiles, name, generation_method, design_rationale,
    predicted_interactions.
    """

    # ── LLM-provided fields ───────────────────────────────────────────────────
    smiles: str = Field(
        ...,
        description=(
            "Valid SMILES string for the molecule. "
            "Must be parseable by RDKit. "
            "Example: 'CCN(CC)CCNC(=O)c1ccc2ncnc(Nc3ccc(F)c(Cl)c3)c2c1'"
        ),
        min_length=2,
    )
    name: Optional[str] = Field(
        default=None,
        description=(
            "Provisional name or identifier for the compound "
            "(e.g. 'Compound-001' or a systematic name)."
        ),
    )
    generation_method: GenerationMethod = Field(
        ...,
        description=(
            "Strategy used to generate this molecule. "
            "One of: scaffold_decoration, bioisostere, fragment_merge, "
            "de_novo, analogue_search, pharmacophore_based."
        ),
    )
    design_rationale: str = Field(
        ...,
        description=(
            "1-2 sentence explanation of why this molecule was designed: "
            "which structural features target which binding site residues."
        ),
        min_length=10,
        max_length=500,
    )
    predicted_interactions: list[str] = Field(
        default_factory=list,
        description=(
            "Predicted key interactions with binding site residues. "
            "Format: '<interaction type> with <residue>' "
            "(e.g. 'H-bond with Met793', 'Pi-stacking with Phe723')."
        ),
        max_length=10,
    )

    # ── RDKit-calculated fields (set by agent, not LLM) ───────────────────────
    molecular_weight: Optional[float] = Field(
        default=None,
        description="Molecular weight in Daltons (calculated by RDKit).",
        ge=0.0,
    )
    logP: Optional[float] = Field(
        default=None,
        description="Wildman-Crippen LogP (octanol/water partition coefficient).",
    )
    qed_score: Optional[float] = Field(
        default=None,
        description=(
            "Quantitative Estimate of Drug-likeness (0.0-1.0). "
            "Calculated by RDKit. Higher = more drug-like."
        ),
        ge=0.0,
        le=1.0,
    )
    sa_score: Optional[float] = Field(
        default=None,
        description=(
            "Synthetic Accessibility score (1.0-10.0). "
            "Calculated by RDKit SA_Score. Lower = easier to synthesise. "
            "Target: < 4.0 for viable drug candidates."
        ),
        ge=1.0,
        le=10.0,
    )
    lipinski_violations: Optional[int] = Field(
        default=None,
        description=(
            "Number of Lipinski Rule-of-Five violations (0-4). "
            "0 = fully drug-like; ≤1 = acceptable; >1 = problematic."
        ),
        ge=0,
        le=4,
    )
    hbd: Optional[int] = Field(
        default=None,
        description="Number of hydrogen bond donors (RDKit).",
        ge=0,
    )
    hba: Optional[int] = Field(
        default=None,
        description="Number of hydrogen bond acceptors (RDKit).",
        ge=0,
    )
    tpsa: Optional[float] = Field(
        default=None,
        description=(
            "Topological Polar Surface Area in Å² (RDKit). "
            "Target: < 140 Å² for oral bioavailability."
        ),
        ge=0.0,
    )
    heavy_atom_count: Optional[int] = Field(
        default=None,
        description="Number of non-hydrogen atoms (RDKit). Used for ligand efficiency.",
        ge=1,
    )
    passes_filters: Optional[bool] = Field(
        default=None,
        description=(
            "Whether this molecule passes all drug-likeness filters. "
            "Set by the agent after RDKit calculation."
        ),
    )

    @field_validator("smiles", mode="before")
    @classmethod
    def strip_smiles(cls, v: str) -> str:
        """Strip whitespace from SMILES strings."""
        return v.strip()

    @field_validator("generation_method", mode="before")
    @classmethod
    def normalise_method(cls, v: str) -> str:
        """
        Normalise generation method to a valid literal value.

        Args:
            v: Raw method string from LLM.

        Returns:
            str: Normalised method.
        """
        synonyms = {
            "scaffold decoration": "scaffold_decoration",
            "scaffold-decoration": "scaffold_decoration",
            "bioisosteric replacement": "bioisostere",
            "bioisosteric": "bioisostere",
            "fragment merging": "fragment_merge",
            "fragment-merge": "fragment_merge",
            "de novo": "de_novo",
            "denovo": "de_novo",
            "analogue": "analogue_search",
            "analog": "analogue_search",
            "pharmacophore": "pharmacophore_based",
        }
        normalised = synonyms.get(v.lower().strip(), v.lower().strip())
        valid = {
            "scaffold_decoration", "bioisostere", "fragment_merge",
            "de_novo", "analogue_search", "pharmacophore_based",
        }
        return normalised if normalised in valid else "de_novo"

    @field_validator("predicted_interactions", mode="before")
    @classmethod
    def coerce_interactions(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    def to_prompt_dict(self) -> dict:
        """
        Return a minimal dict for use in Docking/Synthesis agent prompts.

        Includes only fields needed by downstream agents (SMILES, name,
        key properties) to conserve token budget.

        Returns:
            dict: Slim molecule representation.
        """
        return {
            "smiles": self.smiles,
            "name": self.name or "unknown",
            "molecular_weight": self.molecular_weight,
            "logP": self.logP,
            "qed_score": self.qed_score,
            "sa_score": self.sa_score,
            "lipinski_violations": self.lipinski_violations,
        }


class FilteringCriteria(BaseModel):
    """
    Drug-likeness filtering thresholds applied during molecule shortlisting.

    Values are read from MoleculeConfig and recorded for reproducibility.
    """

    max_molecular_weight: float = Field(
        default=500.0,
        description="Maximum molecular weight in Daltons (Lipinski Ro5).",
        ge=100.0,
        le=1000.0,
    )
    max_logp: float = Field(
        default=5.0,
        description="Maximum calculated LogP (Lipinski Ro5).",
    )
    max_hbd: int = Field(
        default=5,
        description="Maximum hydrogen bond donors (Lipinski Ro5).",
        ge=0,
    )
    max_hba: int = Field(
        default=10,
        description="Maximum hydrogen bond acceptors (Lipinski Ro5).",
        ge=0,
    )
    min_qed_score: float = Field(
        default=0.5,
        description="Minimum QED score threshold (0.0-1.0).",
        ge=0.0,
        le=1.0,
    )
    max_sa_score: float = Field(
        default=4.0,
        description="Maximum synthetic accessibility score (1.0-10.0).",
        ge=1.0,
        le=10.0,
    )
    max_lipinski_violations: int = Field(
        default=1,
        description="Maximum number of Lipinski Ro5 violations allowed.",
        ge=0,
        le=4,
    )


class LLMMoleculeOutput(BaseModel):
    """
    Intermediate schema for the LLM's raw molecule design output.

    The LLM provides SMILES + design metadata; the agent then uses RDKit
    to calculate properties and construct the full GeneratedMolecule objects.
    This schema validates only the LLM-provided fields.
    """

    generated_molecules: list[dict] = Field(
        ...,
        description=(
            "List of molecule dicts with at minimum: smiles, generation_method, "
            "design_rationale. Name and predicted_interactions are optional."
        ),
        min_length=1,
    )
    design_strategy: Optional[str] = Field(
        default=None,
        description="Overall design strategy description.",
    )
    reference_scaffold: Optional[str] = Field(
        default=None,
        description="Core scaffold SMILES if a scaffold-based approach was used.",
    )

    @field_validator("generated_molecules", mode="before")
    @classmethod
    def coerce_molecules(cls, v: object) -> list:
        """Ensure molecules is a non-empty list."""
        if v is None:
            return []
        if not isinstance(v, list):
            return []
        return v


class MoleculeDesignResponse(BaseModel):
    """
    Full output schema for the Molecule Designer agent.

    Combines LLM-generated SMILES with RDKit-calculated properties.
    Contains both the full candidate set and the shortlisted top molecules.
    """

    generated_molecules: list[GeneratedMolecule] = Field(
        ...,
        description=(
            "All generated molecules (after RDKit property calculation). "
            "Includes both passing and failing filter candidates."
        ),
        min_length=1,
    )
    shortlisted_molecules: list[GeneratedMolecule] = Field(
        default_factory=list,
        description=(
            "Top N molecules that passed all drug-likeness filters, "
            "sorted by QED score descending. Passed to docking agent."
        ),
    )
    shortlisted_count: int = Field(
        default=0,
        description="Number of molecules in the shortlist.",
        ge=0,
    )
    filtering_criteria: FilteringCriteria = Field(
        default_factory=FilteringCriteria,
        description="Drug-likeness thresholds applied during shortlisting.",
    )
    design_strategy: Optional[str] = Field(
        default=None,
        description="Overall molecular design strategy used.",
    )
    reference_scaffold: Optional[str] = Field(
        default=None,
        description="Core scaffold SMILES used for scaffold-based design.",
    )
    generation_failures: int = Field(
        default=0,
        description=(
            "Number of SMILES strings that failed RDKit parsing. "
            "High values indicate the LLM is generating invalid chemistry."
        ),
        ge=0,
    )

    @field_validator("shortlisted_molecules", mode="before")
    @classmethod
    def coerce_shortlist(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    def to_prompt_dict(self) -> dict:
        """
        Return a minimal dict for Docking agent prompt.

        Includes only shortlisted molecules (slim representation) to
        conserve token budget.

        Returns:
            dict: Token-efficient representation.
        """
        return {
            "shortlisted_molecules": [
                m.to_prompt_dict() for m in self.shortlisted_molecules
            ],
            "shortlisted_count": self.shortlisted_count,
            "design_strategy": self.design_strategy,
        }


# ─────────────────────────────────────────────────────────────────────────────
# Synthesis Evaluator schemas (OPTIONAL MODULE)
# ─────────────────────────────────────────────────────────────────────────────

class SynthesisRoute(BaseModel):
    """
    A proposed synthetic route for a single drug candidate.

    Produced by the optional Synthesis Evaluator agent when
    FeatureFlags.ENABLE_CHEMICAL_SYNTHESIS is True.
    """

    smiles: str = Field(
        ...,
        description="SMILES of the molecule this route applies to.",
        min_length=2,
    )
    sa_score: float = Field(
        ...,
        description=(
            "RDKit Synthetic Accessibility score (1.0-10.0). "
            "Calculated before LLM call; used to contextualise the LLM's route."
        ),
        ge=1.0,
        le=10.0,
    )
    estimated_steps: int = Field(
        ...,
        description="Estimated number of synthetic steps from starting materials.",
        ge=1,
        le=30,
    )
    starting_materials: list[str] = Field(
        ...,
        description=(
            "List of commercially available starting materials "
            "(common names or IUPAC names)."
        ),
        min_length=1,
    )
    key_reactions: list[str] = Field(
        default_factory=list,
        description=(
            "Key reaction types in the route "
            "(e.g. 'reductive amination', 'Suzuki coupling')."
        ),
    )
    route_description: str = Field(
        ...,
        description=(
            "Step-by-step synthesis outline with reagents and conditions. "
            "Written as a numbered list."
        ),
        min_length=20,
        max_length=3000,
    )
    feasibility: FeasibilityLevel = Field(
        ...,
        description=(
            "Subjective feasibility assessment: "
            "'high' (≤5 steps, standard chemistry), "
            "'medium' (6-8 steps or specialist steps), "
            "'low' (>8 steps or hazardous/expensive reagents)."
        ),
    )
    estimated_yield_percent: Optional[int] = Field(
        default=None,
        description=(
            "Estimated overall yield percentage for the full route. "
            "Null if not estimated."
        ),
        ge=1,
        le=100,
    )

    @field_validator("starting_materials", mode="before")
    @classmethod
    def coerce_materials(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    @field_validator("key_reactions", mode="before")
    @classmethod
    def coerce_reactions(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    @field_validator("feasibility", mode="before")
    @classmethod
    def normalise_feasibility(cls, v: str) -> str:
        """
        Normalise feasibility to high/medium/low.

        Args:
            v: Raw feasibility string from LLM.

        Returns:
            str: Normalised feasibility level.
        """
        synonyms = {
            "easy": "high",
            "straightforward": "high",
            "moderate": "medium",
            "challenging": "low",
            "difficult": "low",
            "hard": "low",
            "very difficult": "low",
        }
        normalised = synonyms.get(v.lower().strip(), v.lower().strip())
        return normalised if normalised in {"high", "medium", "low"} else "medium"

    @field_validator("sa_score", mode="before")
    @classmethod
    def clamp_sa_score(cls, v: object) -> float:
        """Clamp SA score to [1.0, 10.0]."""
        try:
            return max(1.0, min(10.0, float(v)))
        except (TypeError, ValueError):
            return 5.0


class SynthesisResponse(BaseModel):
    """
    Full output schema for the Synthesis Evaluator agent.

    When synthesis is disabled (FeatureFlags.ENABLE_CHEMICAL_SYNTHESIS=False),
    the agent returns this schema with synthesis_enabled=False and an
    empty synthesis_routes list.
    """

    synthesis_routes: list[SynthesisRoute] = Field(
        default_factory=list,
        description=(
            "Proposed synthetic routes for each shortlisted molecule. "
            "Empty when synthesis_enabled=False."
        ),
    )
    synthesis_enabled: bool = Field(
        ...,
        description=(
            "True if synthesis evaluation was performed. "
            "False if ENABLE_CHEMICAL_SYNTHESIS=False."
        ),
    )
    message: Optional[str] = Field(
        default=None,
        description=(
            "Status message. Required when synthesis_enabled=False to explain "
            "why synthesis was skipped."
        ),
    )
    recommended_candidate: Optional[str] = Field(
        default=None,
        description=(
            "SMILES of the most synthetically accessible candidate. "
            "Null when synthesis_enabled=False."
        ),
    )

    @field_validator("synthesis_routes", mode="before")
    @classmethod
    def coerce_routes(cls, v: object) -> list:
        """Accept None as empty list."""
        if v is None:
            return []
        return v

    def to_prompt_dict(self) -> dict:
        """
        Return a compact dict for Report Compiler prompt.

        Returns:
            dict: Synthesis status and top route summaries.
        """
        if not self.synthesis_enabled:
            return {
                "synthesis_enabled": False,
                "message": self.message,
            }
        return {
            "synthesis_enabled": True,
            "recommended_candidate": self.recommended_candidate,
            "routes_count": len(self.synthesis_routes),
            "top_routes": [
                {
                    "smiles": r.smiles,
                    "estimated_steps": r.estimated_steps,
                    "feasibility": r.feasibility,
                    "sa_score": r.sa_score,
                }
                for r in self.synthesis_routes[:3]
            ],
        }

    model_config = {
        "json_schema_extra": {
            "example": {
                "synthesis_routes": [
                    {
                        "smiles": "CCN(CC)CCNC(=O)c1ccc2ncnc(Nc3ccc(F)c(Cl)c3)c2c1",
                        "sa_score": 2.8,
                        "estimated_steps": 6,
                        "starting_materials": ["4-amino-3-chlorofluorobenzene",
                                               "4-chloro-6-nitroquinazoline"],
                        "key_reactions": ["SNAr substitution", "reductive amination",
                                          "amide coupling"],
                        "route_description": (
                            "1. SNAr reaction of 4-chloro-6-nitroquinazoline with "
                            "4-amino-3-chlorofluorobenzene (DMF, 80°C, 12h). "
                            "2. Reduction of nitro group (Fe/AcOH). "
                            "3. Amide coupling with N,N-diethylaminopropanoic acid."
                        ),
                        "feasibility": "high",
                        "estimated_yield_percent": 35,
                    }
                ],
                "synthesis_enabled": True,
                "recommended_candidate": (
                    "CCN(CC)CCNC(=O)c1ccc2ncnc(Nc3ccc(F)c(Cl)c3)c2c1"
                ),
            }
        }
    }